### ISSUE TITLE
在minirouter.js里面移除getFullPath函数

### ISSUE THREAD

**Issue by linzb93** [levin-du/minirouter#1]
我在minirouter.js里面移除getFullPath函数，并把63行的getFullPath(nextPath)换成nextPath，在你的demo上运行是正常的。
我比较了getFullPath(nextPath)和nextPath的值，虽然在首次加载时二者不相等，之后hash值变化时才相等。但是首次加载后再执行getRoute函数时，path.hash值是相同的。
所以getFullPath是多余的，还是有哪种特殊情况我没有考虑到，还请告知，谢谢。

**Comment by linzb93** [comment]
抱歉，我刚才比较了nextPath和getFullPath(nextPath)的值，首次加载时是不相等的(⊙﹏⊙)b

**Comment by levin-du** [comment]
确实是多余的, 你看的很仔细！我应该尝试做一下单元测试的。
